# Generated by Django 2.2.16 on 2023-04-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
