# Generated by Django 2.2.16 on 2023-04-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230412_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='color',
            field=models.CharField(blank=True, max_length=7, verbose_name='color in Hex'),
        ),
    ]
