# Generated by Django 2.2.16 on 2023-04-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20230412_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='recipes.Tags', verbose_name='Тэги'),
        ),
    ]
